header:
  version: 18

machine: qemuarm64
distro: poky
target:
  - core-image-minimal

repos:
  meta-openembedded:
    path: sources/meta-openembedded
    url: https://github.com/openembedded/meta-openembedded.git
    branch: scarthgap
    layers:
      meta-networking:
      meta-oe:
      meta-python:

  poky:
    path: sources/poky
    url: https://github.com/yoctoproject/poky.git
    branch: scarthgap
    layers:
      meta:
      meta-poky:

local_conf_header:
  debug-tweaks: |
    EXTRA_IMAGE_FEATURES = "allow-root-login empty-root-password serial-autologin-root"

  demo-conf: |
    IMAGE_INSTALL:append = " util-linux-agetty htop"
